version: "3.8"
services:
    mongo:
        container_name: mongo_compose
        image: mongo
        restart: unless-stopped
        volumes:
            - db-data:/var/lib/mongodb/data
        networks: 
            - custom
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=quesitoUser
            - MONGO_INITDB_ROOT_PASSWORD=SecretCheese1234
        ports:
            - "27017:27017"
            
    express:
        image: mongo-express
        container_name: mexpress_compose
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
            - ME_CONFIG_MONGODB_ADMINUSERNAME=quesitoUser
            - ME_CONFIG_MONGODB_ADMINPASSWORD=SecretCheese1234
            - ME_CONFIG_BASICAUTH_USERNAME=DASistemas
            - ME_CONFIG_BASICAUTH_PASSWORD=ex-especial567
        depends_on: 
            - mongo
        ports: 
            - "8081:8081"
        networks: 
            - custom
    goapp:
        container_name: goapp
        build: 
            context: . 
            dockerfile: Dockerfile.scrapper
        depends_on:
            - mongo
        networks:
            - custom
    goapi:
        container_name: goapi
        build:
            context: .
            dockerfile: Dockerfile.api
        depends_on:
            - mongo
        networks:
            - custom
        ports:
            - "7777:7777"
        restart: unless-stopped

volumes:
    db-data:
    
networks:
    custom:
        driver: bridge
    
